### ISSUE TITLE
Tłumaczenie.

### ISSUE THREAD

**Issue by Weakus** [gammerce/plugin-sourcemod#1]
[SM] Exception reported: Language phrase "Log In" not found (arg 6)

Jeszcze czegoś będzie brakować w tym sklepie? Czy za każdym razem mam w własnym zakresie przeglądać pliki i dodawać brakujących elementów ;/

**Comment by budziam** [comment]
Brzmi jakbyś nie wrzucił nowej wersji pluginu. Stara wersja wymagała tego tłumaczenia, a nowa już nie.

**Comment by Weakus** [comment]
Na odwrót, nowa tego wymaga, stara już nie. ;P

**Comment by budziam** [comment]
W wersji 3.6.0 został usunięty kawałek kodu, który wyświetlał w menu początkowym opcję zalogowania się.

![image](https://user-images.githubusercontent.com/10908895/71125161-c20c4480-21e6-11ea-9d38-8d58f140ffb4.png)

Z tego też powodu zostało usunięte tłumaczenie dla frazy "Log In"

**Comment by Weakus** [comment]
56 "Shop SMS" (3.6.0) by SeeK
57 "Shop SMS: Service: VIP" (3.6.0) by SeeK
:<

**Comment by budziam** [comment]
Z jakiej wersji sourcemod korzystasz?

**Comment by Weakus** [comment]
1.10, więc najnowszy.

**Comment by budziam** [comment]
Postawiłem u siebie swieży serwer CSGO z sourcemod w wersji 1.10 na który wgrałem sklepsms w wersji 3.6.0. Jako gracz zakupiłem usługę VIP w trakcie gry. W żadnym momencie nie pojawił się błąd, który opisujesz.
Żeby móc naprawić ten problem muszę być w stanie odtworzyć go u siebie.

**Comment by Weakus** [comment]
Dodałem brakującą frazę, nie spamuje, jakiegoś dużego kłopotu to nie robi 🙄
