### ISSUE TITLE
Errory w konsoli

### ISSUE THREAD

**Issue by xdbx1021** [gammerce/plugin-sourcemod#2]
Co jakiś czas wywala się błąd w konsoli:

L 04/12/2020 - 10:34:29: [SM] Exception reported: Plugin handle 850085 is invalid (error 1)
L 04/12/2020 - 10:34:29: [SM] Blaming: shopsms.smx
L 04/12/2020 - 10:34:29: [SM] Call stack trace:
L 04/12/2020 - 10:34:29: [SM]   [0] GetFunctionByName
L 04/12/2020 - 10:34:29: [SM]   [1] Line 177, include/shopsms/server.inc::ExtractServices
L 04/12/2020 - 10:34:29: [SM]   [2] Line 95, include/shopsms/server.inc::Server_LoadConfigCallback

meta list:

[01] SourceMod (1.11.0.6522) by AlliedModders LLC
[02] BanId Fix (1.0) by Phoenix (˙·٠●Феникс●٠·˙)
[03] SDK Tools (1.11.0.6522) by AlliedModders LLC
[04] CS Tools (1.11.0.6522) by AlliedModders LLC
[05] PTaH (1.1.1) by Phoenix (˙·٠●Феникс●٠·˙)
[06] SteamWorks Extension (1.2.3) by Kyle Sanderson
[07] SDK Hooks (1.11.0.6522) by AlliedModders LLC

Wersja sklepu: 3.9.0

**Comment by budziam** [comment]
Z jakiej wersji SM korzystasz?

**Comment by xdbx1021** [comment]
Udało się uniknąć tego błędu.
Po zmianie tokenu 5 raz udało się. 

Wersja sklepu na SM 1.10

**Comment by budziam** [comment]
Zrobienie sklepu kompatybilnego z wersją 1.11 spowoduje porzucenie wsparcia dla wersji poniżej 1.10. Muszę pierwsze zrobić rozeznanie ile osób korzysta z sourcemod w wersji starszej niż 1.10

**Comment by budziam** [comment]
Pojawiła się nowa wersja sklepu [3.10.0](https://github.com/gammerce/plugin-sourcemod/releases/tag/3.10.0), która wspiera SM `1.11`

**Comment by xdbx1021** [comment]
teraz co każdą zmianę mapy wywala taki błąd:

L 04/24/2020 - 17:53:40: [shopsms.smx] json_decode: unexpected data after end of structure at position 55
L 04/24/2020 - 17:53:40: [shopsms.smx] json_decode: expected key string at position 807

**Comment by budziam** [comment]
Jak rozumiem wgrałeś wersję skompilowaną pod SM 1.11?

**Comment by xdbx1021** [comment]
Tak wersja sklepu 3.10.0 na SM 1.11

**Comment by budziam** [comment]
Wygląda na to, że biblioteka do obsługi danych w formacie JSON nie działa prawidłowo pod `SM 1.11`. Dam znać autorowi o problemie. Niewiele więcej mogę zrobić.

**Comment by budziam** [comment]
Problem rozwiązany w wersji [3.10.1](https://github.com/gammerce/plugin-sourcemod/releases/tag/3.10.1)
