### ISSUE TITLE
ss_reload

### ISSUE THREAD

**Issue by p4strike** [gammerce/plugin-sourcemod#3]
Witam,

po wpisaniu komendy ss_reload takie coś w konsoli:
[shop_sms/shopsms.smx] json_decode: expected key string at position 526
[shop_sms/shopsms.smx] Error: 20-1. An error occured while loading server's config.

Oraz osoba która zakupi VIPA nie otrzymuje go. Jest to najnowsza wersja na SM 1.11.

**Comment by budziam** [comment]
Cześć,
dzięki za zgłoszenie. Problem został rozwiązany w wersji [3.10.1](https://github.com/gammerce/plugin-sourcemod/releases/tag/3.10.1)
