### ISSUE TITLE
"Moje usługi"

### ISSUE THREAD

**Issue by Vakos321575** [gammerce/plugin-sourcemod#5]
Wersja SM: 3.10.2
Wersja www: v3.16.2

1) Gdy nadamy ręcznie usługę przez panel Admina to na serwerze pokazuje, że dana osoba nie ma żadnej usługi (choć normalnie posiada uprawnienia i dostęp do np: VIP'a) -> !sklepsms -> 2. Pokaż moje usługi. 
Gdy gracz kupi samodzielnie usługę to wtedy po wejściu w zakładkę pokaż moje usługi pokazuje do kiedy została wykupiona.

2) Proponuję dodać dodatkowo komendę np; !koniec (bądź cvar w którym sami będziemy mogli ustalić komendę) która pokaże nam do kiedy mamy aktywną usługę.

**Comment by Vakos321575** [comment]
@budziam Problem jest stały. Od momentu zgłoszenia (czyli 18 dni temu) do dziś problem nadal występuje.
Sprawdziłem jeszcze raz przed chwilą - dodałem usługę w sklepie, zmieniła się mapa -> !sklepsms -> pokaż moje usługi -> informacja o braku aktywnych usług

**Comment by budziam** [comment]
Muszę spróbować odtworzyć ten błąd, żeby być w stanie ocenić skąd on się bierze. Czy mógłbyś przyznać mi dostęp do panelu admina w twoim sklepie SMS? Dane mógłbyś wysłać na adres email seek@sklep-sms.pl

**Comment by Vakos321575** [comment]
Znalazłem błąd dlaczego tak się dzieje.
Gdy dodamy usługę na SID który zaczyna się na: STEAM_0:1 -> to w !sklepsms nie pokaże czasu trwania usługi.
Gdy dodamy usługę na SID który zaczyna się na: STEAM_1:1 -> wtedy pokazuje normalnie czas trwania.

Warto by było dodać aby sklep brał pod uwagę 2 formy.

**Comment by xdbx1021** [comment]
Ten "błąd" możesz odtworzyć w taki sposób:
Moje STEAM ID to STEAM_0:1:2682857
W CSGO jest ono zmienione bo i wygląda tak: STEAM_1:1:2682857

Osoby grające w tą grę nie wiedzą, że sprawdzając SID na www jest inny w CSGO.
Wystarczy aby sklep równał STEAM_0: z STEAM_1:

**Comment by xdbx1021** [comment]
Długo jeszcze będziemy czekać na poprawę? Rozumiem że można mieć mniej czasu, ale to już minęło pół roku! 
Zacznij w końcu poprawiać te błędy.

Widzę że ważne jest aby tylko opłacać licencję sklepu
Wyjebane w poprawki/nowości (przecież ludzie opłacają)

**Comment by budziam** [comment]
Problem zostsał naprawiony w wersji https://github.com/gammerce/plugin-sourcemod/releases/tag/3.11.0
